[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
wildlifetracking = "0x62123c424fcc3ae4097819a20090407be38af07bf4ec50c32a44360d389f46de"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "devnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
